spring:
  main.banner-mode: 'off'
  profiles.active: local-sandbox
---
spring:
  profiles: local-sandbox
config:
  pollingInterval: 5000
  inputFolderPath: xyzbank/input
  errorFolderPath: xyzbank/error
  processedFolderPath: xyzbank/processed
  auditFolderPath: xyzbank/audit
---
spring:
  profiles: dev
config:
  pollingInterval: 5000
  inputFolderPath: xyzbank/input
  errorFolderPath: xyzbank/error
  processedFolderPath: xyzbank/processed
  auditFolderPath: xyzbank/audit
---
spring:
  profiles: staging
config:
  pollingInterval: 5000
  inputFolderPath: xyzbank/input
  errorFolderPath: xyzbank/error
  processedFolderPath: xyzbank/processed
  auditFolderPath: xyzbank/audit
---
spring:
  profiles: production
config:
  pollingInterval: 5000
  inputFolderPath: xyzbank/input
  errorFolderPath: xyzbank/error
  processedFolderPath: xyzbank/processed
  auditFolderPath: xyzbank/audit 